baseURL = 'alireza-mandegar.github.io/LightByte'
languageCode = 'en-us'
title = 'LightByte'
theme = 'nightfall'

[menu]
[[menu.header]]
name = "posts"
weight = 0
url = "posts"


[params]
user = "LightByte"
hostname = "github.io"
footerHtml = 'Threat Not Found... For Now.'
[params.author]
name = "Wellcome to LightByte: Where Logs Confess and Endpoints Spill Their Secrets."
email = "hello@to.you"
avatar = "https://alireza-mandegar.github.io/LightByte/authors/admin/avatar.png"
avatarSize = "size-s"

readingTime = true
published = true

sitedescription = 'LightByte'

[[params.social]]
key = 0
name = "github"
url = "https://github.com/alireza-mandegar"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/alirezamandegar/"
aria = "LinkedIn Profile"
